name: "Deploy :: Local"

on:
  workflow_dispatch:
    inputs:
      deploy_vpc:
        description: "Deploy VPC resources"
        required: false
        type: boolean
      create_database:
        description: "Create Database"
        required: false
        type: boolean
      deploy_database_ddl:
        description: "Deploy Database DDL"
        required: false
        type: boolean
      lcl_stage:
        description: Local stage name
        default: "dave"

env:
  REGION: uk
  STAGE: lcl
  PROJECT: tutorseekers
  AWS_REGION: eu-west-2
  NODE_VERSION: 20.10

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy-vpc-resources:
    if: ${{ inputs.deploy_vpc }}
    name: Deploy vpc-resources
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Verify AWS CLI availability
        run: aws --version

      - name: Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk

      - name: Install
        run: yarn workspaces focus @tutorseekers/base-infrastructure

      - name: Install everything
        run: yarn

      - name: Synth Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk synth -c region=uk -c stage=lcl "$PROJECT-uk-lcl-vpc"

      - name: Deploy Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk deploy -c region=uk -c stage=lcl "$PROJECT-uk-lcl-vpc"

  create-database:
    if: ${{ inputs.create_database }}
    name: Deploy database
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Verify AWS CLI availability
        run: aws --version

      - name: Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: 20.10
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk

      #
      - name: Install
        run: yarn workspaces focus @tutorseekers/base-infrastructure

      - name: Install everything
        run: yarn

      - name: Synth Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk synth -c region=uk -c stage=lcl -c lclStage=${{github.actor}}  "$PROJECT-uk-lcl-create-database"

      - name: Deploy Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk deploy -c region=uk -c stage=lcl -c lclStage=${{github.actor}}  "$PROJECT-uk-lcl-create-database"

  deploy_database_ddl:
    if: ${{ inputs.deploy_database_ddl }}
    name: Deploy database
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Chmod to 777
        run: chmod -R 777 apps/database

      - name: list the directory
        run: ls -ltr apps/database

      - name: Copy the DDL Files to the S3 Bucket
        run: aws s3 cp apps/database s3://${{env.PROJECT}}-${{env.REGION}}-${{github.actor}}-deploy-bucket/ --recursive
      # run: aws s3 sync apps/database s3://${{env.PROJECT}}-${{env.REGION}}-${{env.STAGE}}-deploy-bucket --acl public-read

      - name: Invoke AWS Lambda by OIDC
        run: aws lambda invoke --function-name ${{env.PROJECT}}-${{env.REGION}}-${{github.actor}}-deploy-database-ddl output.txt
      #   uses: y5347M/invoke-aws-lambda-oidc@v1
      #   with:
      #     aws-region: 'us-west-2'
      #     role-to-assume: 'arn:aws:iam::123456789012:role/MyRole'
      #     function-name: 'my-lambda-function'
      #     payload: '{"key1":"value1","key2":"value2"}'

      # - name: Output Lambda Response
      #   run: echo "Lambda Response: ${{ steps.invoke.outputs.lambda-invoke-response }}"

      # - name: Run the database deploy lambda
      #   id: database-deploy
      #   uses: gagoar/invoke-aws-lambda@master
      #   with:
      #     FunctionName: ${{env.PROJECT}}-${{env.REGION}}-${{env.STAGE}}-deploy-database-ddl
      #     LogType: Tail
      #     Payload: "{ }"
      # - name: Show the deploy status
      #   run: echo "${{ fromJSON(steps.database-deploy.outputs.response).LogResult }}"
