name: "Deploy :: Local"

on:
  workflow_dispatch:
    inputs:
      deploy_vpc:
        description: "Deploy VPC resources"
        required: false
        type: boolean
      create_database:
        description: "Create Database"
        required: false
        type: boolean
      deploy_database_ddl:
        description: "Deploy Database DDL"
        required: false
        type: boolean

env:
  REGION: uk
  STAGE: lcl
  PROJECT: tutorseekers
  AWS_REGION: eu-west-2
  NODE_VERSION: 20.10

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy-vpc-resources:
    if: ${{ inputs.deploy_vpc }}
    name: Deploy vpc-resources
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Verify AWS CLI availability
        run: aws --version

      - name: Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk

      - name: Install
        run: yarn workspaces focus @tutorseekers/base-infrastructure

      - name: Install everything
        run: yarn

      - name: Synth Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk synth -c region=uk -c stage=lcl "$PROJECT-uk-lcl-vpc"

      - name: Deploy Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk deploy -c region=uk -c stage=lcl "$PROJECT-uk-lcl-vpc"

  create-database:
    if: ${{ inputs.create_database }}
    name: Deploy database
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Verify AWS CLI availability
        run: aws --version

      - name: Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: 20.10
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk

      #
      - name: Install
        run: yarn workspaces focus @tutorseekers/base-infrastructure

      - name: Install everything
        run: yarn

      - name: Synth Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk synth -c region=uk -c stage=lcl "$PROJECT-uk-lcl-create-database"

      - name: Deploy Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk deploy -c region=uk -c stage=lcl "$PROJECT-uk-lcl-create-database"

  deploy_database_ddl:
    if: ${{ inputs.deploy_database_ddl }}
    name: Deploy database
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Copy the DDL Files to the S3 Bucket
        run: aws s3 sync apps/database s3://${{env.PROJECTS}}-${{env.REGION}}-${{env.STAGE}}-deploy-bucket

      - name: Run the lambda to load the DDL
        run: echo "Run the lambda to load the DDL"
