name: "Local :: Teardown"

on:
  workflow_dispatch:
    inputs:
      delete_vpc:
        description: "Delete VPC resources"
        required: false
        type: boolean
      delete_database:
        description: "Delete Database"
        required: false
        type: boolean

env:
  REGION: uk
  STAGE: lcl
  PROJECT: tutorseekers
  AWS_REGION: eu-west-2
  NODE_VERSION: 20.10

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  delete_database:
    # if: ${{ inputs.delete_database }}
    name: Teardown database
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Verify AWS CLI availability
        run: aws --version

      - name: Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: 20.10
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk

      #
      - name: Install
        run: yarn workspaces focus @tutorseekers/base-infrastructure

      - name: Install everything
        run: yarn

      - name: Synth Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk synth -c region=uk -c stage=lcl -c lclStage=${{github.actor}}  "$PROJECT-uk-$(echo ${{ github.actor }} | awk '{print tolower($0)}')-create-database"

      - name: Destroy Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk destroy -c region=uk -c stage=lcl -c lclStage=${{github.actor}}  "$PROJECT-uk-$(echo ${{ github.actor }} | awk '{print tolower($0)}')-create-database"

  teardown-vpc-resources:
    # if: ${{ inputs.delete_vpc }}
    name: Teardown vpc-resources
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Verify AWS CLI availability
        run: aws --version

      - name: Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk

      - name: Install
        run: yarn workspaces focus @tutorseekers/base-infrastructure

      - name: Install everything
        run: yarn

      - name: Synth Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk synth -c region=uk -c stage=lcl -c lclStage=$(echo ${{ github.actor }} | awk '{print tolower($0)}') "$PROJECT-uk-lcl-vpc"

      - name: Teardown Stack
        run: ls && cd apps/2-base-infrastructure && ls && yarn cdk destroy -c region=uk -c stage=lcl -c lclStage=$(echo ${{ github.actor }} | awk '{print tolower($0)}') "$PROJECT-uk-lcl-vpc"
