name: "Deploy :: Local"

on:
  workflow_dispatch:
    inputs:
      deploy_vpc:
        description: "Deploy VPC resources"
        required: false
        type: boolean
      deploy_database:
        description: "Deploy Database resources"
        required: false
        type: boolean
      deploy_database_ddl:
        description: "Deploy Database DDL"
        required: false
        type: boolean

env:
  REGION: uk
  PROJECT: tutorseekers
  AWS_REGION: eu-west-2
  NODE_VERSION: 20.10

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy-vpc-resources:
    if: ${{ inputs.deploy_vpc }}
    name: Deploy vpc-resources
    runs-on: ubuntu-latest
    # timeout-minutes: ${{ fromJSON(vars.DEFAULT_GHA_TIMEOUT_MIN) }}
    # environment: ${{ inputs.github-environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install corepack
        run: npm install -g corepack

      - name: Enable corepack
        run: corepack enable

      - name: Verify AWS CLI availability
        run: aws --version

      - name: Setup Node & Cache
        uses: actions/setup-node@v3
        with:
          node-version: 20.10
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk

      #
      - name: Install
        run: yarn workspaces focus @tutorseekers/base-infrastructure

      - name: Install everything
        run: yarn

      - name: Synth Stack
        working-directory: apps/2-base-infrastructure
        run: |
          yarn synth -c region=uk -c stage=lcl '${PROJECT}-uk-lcl-vpc'

      - name: Deploy Stack
        run: |
          yarn deploy -c region=uk -c stage=lcl '${PROJECT}-uk-lcl-vpc'

# jobs:
#   deploy-locally:
#     uses: ./.github/workflows/deploy-base-infrastructure.yml
#     with:
#       project: tutorseekers
#       github-environment: LocalPreview
#       stage: $(echo ${{ github.actor }} | awk '{print tolower($0)}')
#       github-author: ${{ github.actor }}
#       region: uk
#       aws_region: eu-west-2
#       deploy_vpc: ${{ inputs.deploy_vpc }}
#       deploy_database: ${{ inputs.deploy_database }}
#       deploy_database_ddl: ${{ inputs.deploy_database_ddl }}
#     secrets:
#       aws-role-arn: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
